            - name: ROS 2 CI Action
  # You may pin to the exact commit or the version.
  # uses: ros-tooling/action-ros-ci@bc41bd38faf06d2c2c4a4a6fa7038916e7ac6083
  uses: ros-tooling/action-ros-ci@0.3.5
  with:
    # Valid JSON content to use as a colcon defaults.yaml file.
#Use a pipe to provide a multiline string.
#See: https://colcon.readthedocs.io/en/released/user/configuration.html#defaults-yaml

    colcon-defaults: # optional, default is 
    # Mixin repository containing the mixin(s) specified through colcon-defaults or colcon-extra-args
    colcon-mixin-repository: # optional, default is https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    # Ignore all files matching this pattern in the coverage report.
It will be injected in colcon-lcov-result --filter option.
Useful for ignoring tests or examples in the coverage report.

    coverage-ignore-pattern: # optional, default is 
    # Additional flags passed to CMake (using colcon build --cmake-args)

    extra-cmake-args: # optional, default is 
    # Arbitrary space-separated additional flags to pass to colcon (build & test).

    colcon-extra-args: # optional, default is 
    # GitHub personal access token (PAT) to use to import the repository.
Useful if the repo is private.
The PAT should have the "repo" scope.

    import-token: # optional, default is 
    # Limit the package(s) to be built and tested.
If left empty this will build and test everything in the workspace - including packages from vcs-repo-file-url imports.
Passing multiple package names is allowed.
Package names can be separated by any whitespace character.

    package-name: # optional, default is 
    # ROS 1 distribution to target for the build.  Will be used both for
`rosdep install` and `source setup.bash`. Either or both of
`target-ros1-distro` and `target-ros2-distro`, but at least one must
be specified. Typically, both are specified when building packages
that rely on both ROS versions, such as the ros1_bridge.

    target-ros1-distro: # optional
    # ROS 2 distribution to target for the build.  Will be used both for
`rosdep install` and `source setup.bash`. Either or both of
`target-ros1-distro` and `target-ros2-distro`, but at least one must
be specified. Typically, both are specified when building packages
that rely on both ROS versions, such as the ros1_bridge.

    target-ros2-distro: # optional
    # Repo file URL passed to vcs to initialize the colcon workspace.
The URL may point to a local file, such as file://path/to/file.txt.
For example, for ROS 2 Rolling source repositories, use:
https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos

    vcs-repo-file-url: # optional, default is 
    # Skip tests and code coverage data processing.
Set to 'true'.

    skip-tests: # optional, default is 
    # Keys to be skipped when installing dependencies via rosdep.
Passing multiple keys is allowed.
Keys names can be separated by any whitespace character.

    rosdep-skip-keys: # optional, default is 
    # Branch or reference to checkout via vcstool.
If unset will use the branch from where this action was triggered.
Scheduled events default to latest commit of default branch.
Set this if you want the scheduled job to run on on a specific branch.

    ref: # optional, default is 
          
