name: ROS-2 CI
on:
  # Run this action whenever a pull request is made
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - directory-fix

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v2
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          install-connext: true
          use-ros2-testing: true
          required-ros-distributions: humble
      # - run: rosinstall_generator robile_safety_features --rosdistro humble --deps-only --deps --upstream-development > /tmp/deps.repos
      # - run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      - run: "sudo pip install py-trees"
      # - run: "sudo apt install ros-humble-py-trees ros-humble-py-trees-ros-interfaces ros-humble-py-trees-ros ros-humble-py-trees-ros-tutorials ros-humble-py-trees-ros-viewer"
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: robile_safety_features
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos
          # vcs-repo-file-url: /tmp/deps.repos
