name: ROS-2 CI
on:
  # Run this action whenever a pull request is made
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v2
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          install-connext: true
          use-ros2-testing: true
          required-ros-distributions: humble
      # - run: rosinstall_generator src/robile_safety_features --rosdistro humble --deps-only --deps --upstream-development > /tmp/deps.repos
      # - run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: src/robile_safety_features
          target-ros2-distro: humble
          # vcs-repo-file-url: /tmp/deps.repos
